### PR TITLE
Use fetch for networking instead of custom http / fs logic

### LINKED ISSUE #5: Use window-fetch for loading content
It'd be nice to consolidate all our resource loading in one place.
As such, we should get rid of the resource loading code from this module and have it use [window-fetch](https://github.com/modulesio/window-fetch).

We should have it require window-fetch by default, and have an option for specifying the fetch implementation for custom stuff.

We'll be making a tradeoff by getting rid of cancellation. We'll still have it act like it's cancelled the request, but fetch will still resolve in the background. This could be addressed later if we introduce the cancellation signal API to window-fetch.
We might also be missing out on exceptions that would normally be thrown inside `open` for invalid protocols and URLs.

Steps:

- [ ] Convert between formdata and fetch body
- [ ] Find mappings between status codes and stuff between xhr and fetch
- [ ] Replace file/HTTP handling inside `open()` with call to `fetch()`
- [ ] Implement `abort()` which sets the aborted status, but doesn't cancel the fetch call
- [ ] Test that it works!

### PR DESCRIPTION
**Pull request by RangerMauve**
Closes #5 

Tests passing.

Needs a bit more cleanup to find unused code paths.
Needs updated docs.

### CODE REVIEW

File: lib/xmlhttprequest.js [hunk 1]
```diff
@@ -112,23 +99,53 @@ function _receiveResponse(response) {
...
-    if (!textResponseType) {
-      _properties.responseBuffers.push(chunk);
-    } else {
-      _properties.responseText = _properties.responseText + chunk;
-    }
-    this.loaded += chunk.length;
+
+  _readyStateChange.call(this, XMLHttpRequest.HEADERS_RECEIVED);
+
+  const isStream = (typeof response.body.pipe) === 'function';
```
Comment (avaer) [inline lib/xmlhttprequest.js]: Is there a better way to detect this with node's modules? And will there always be a `body`?

File: lib/xmlhttprequest.js [hunk 2]
```diff
@@ -299,74 +316,29 @@ class XMLHttpRequest extends XMLHttpRequestEventTarget {
...
-          const errorEvent = new Event('error');
-          errorEvent.error = err;
-          this.dispatchEvent(errorEvent);
-        });
+    const {uri, method, headers} = _properties;
+
+      // Convert body to something fetch can consume
+    const toSendBody = body;
+    if (body instanceof FormData) {
+      toSendBody = {};
```
Comment (avaer) [inline lib/xmlhttprequest.js]: I don't think this code is legal, per the above `const`.

File: package.json [hunk 3]
```diff
@@ -11,12 +11,13 @@
   },
   "main": "./lib/index.js",
   "scripts": {
-    "lint": "npm install && eslint lib/**/*.js test/**/*.js",
-    "test": "npm install && mocha test/**/*.js"
+    "lint": "eslint --fix lib/**/*.js test/**/*.js",
```
Comment (avaer) [inline package.json]: Would rather not impose editor config here.

File: lib/xmlhttprequest.js [hunk 4]
```diff
@@ -191,13 +208,13 @@ class XMLHttpRequest extends XMLHttpRequestEventTarget {
       method: 'get',
       responseHeaders: {},
       responseBuffers: [],
-      responseText: new String(),
+      responseText: '',
       responseType: '',
       requestHeaders: {
-        'X-Requested-With': 'XMLHttpRequest',
+        'X-Requested-With': 'XMLHttpRequest'
```
Comment (avaer) [inline lib/xmlhttprequest.js]: Most exokit codebases use dangling comma.

File: lib/xmlhttprequest.js (hunk 1 above)
Comment (RangerMauve) [reply lib/xmlhttprequest.js]: There _should_ always be a body, but I'll check it out.

File: lib/xmlhttprequest.js (hunk 2 above)
Comment (RangerMauve) [reply lib/xmlhttprequest.js]: Good catch!

File: package.json (hunk 3 above)
Comment (RangerMauve) [reply package.json]: So, remove the `--fix` flag?

File: lib/xmlhttprequest.js (hunk 4 above)
Comment (RangerMauve) [reply lib/xmlhttprequest.js]: Ah, the eslint config changed it with `--fix`. I'll change whatever rule was causing that.

I personally prefer having the comma, too. :)

File: package.json (hunk 3 above)
Comment (avaer) [reply package.json]: Yup, that works.

File: lib/xmlhttprequest.js [hunk 5]
```diff
@@ -97,11 +80,15 @@ function _readyStateChange(readyState) {
 
 function _receiveResponse(response) {
   const _properties = this._properties;
-  const statusCode = response.statusCode;
+  const statusCode = response.status;
   this.status = statusCode;
   this.statusText = HTTP_STATUS_CODES[statusCode];
-  _properties.responseHeaders = response.headers;
-  const contentLength = response.headers['content-length'] || '0';
+  const headers = {};
```
Comment (avaer) [inline lib/xmlhttprequest.js:85]: What is the purpose of the copy here? `fetch` instance should be owned by our implementation so we can mangle it, right?

File: lib/xmlhttprequest.js [hunk 6]
```diff
@@ -112,23 +99,53 @@ function _receiveResponse(response) {
...
-    if (!textResponseType) {
-      _properties.responseBuffers.push(chunk);
-    } else {
-      _properties.responseText = _properties.responseText + chunk;
-    }
-    this.loaded += chunk.length;
+
+  _readyStateChange.call(this, XMLHttpRequest.HEADERS_RECEIVED);
+
+  const isStream = response.body && ((typeof response.body.pipe) === 'function');
```
Comment (avaer) [inline lib/xmlhttprequest.js:104]: If the `fetch` implementation set is standard, this will never be true, correct? This isn't necessarily a problem, just wanted to confirm.

File: lib/xmlhttprequest.js [hunk 7]
```diff
@@ -299,74 +316,29 @@ class XMLHttpRequest extends XMLHttpRequestEventTarget {
...
-          body.pipe(client);
-        } else {
-          client.end();
-        }
-        client.on('error', err => {
-          const errorEvent = new Event('error');
-          errorEvent.error = err;
-          this.dispatchEvent(errorEvent);
-        });
+    const {uri, method, headers} = _properties;
```
Comment (avaer) [inline lib/xmlhttprequest.js:318]: Couple of thing things on the left hand side that seem not covered here, which could cause regressions in sites expecting conformance (why they are there in the first place!):

- `gzip`  transparent decode -- is it expected to be handled by the fetch implementation?
- upload support -- only `FormData` looks whitelisted, and not passed through as `FormData`. I know we define that class ourselves, but I think it's fine to pass it through.

File: lib/xmlhttprequest.js (hunk 6 above)
Comment (RangerMauve) [reply lib/xmlhttprequest.js:104]: Yes! After we get the initial stuff working, we'll need to detect the WhatWG stream responses.

File: lib/xmlhttprequest.js (hunk 7 above)
Comment (RangerMauve) [reply lib/xmlhttprequest.js:318]: `gzip` support is indeed left to the fetch implementation to handle.

You're right about the FormData! It should just be passed in for fetch to deal with it.

File: lib/xmlhttprequest.js (hunk 5 above)
Comment (RangerMauve) [reply lib/xmlhttprequest.js:85]: I think it's that these headers are an Object mapping header keys to header values, whereas fetch uses a Headers object that has methods for getting and setting headers.

Comment (avaer) [reply lib/xmlhttprequest.js:85]: Makes sense, thanks.

File: lib/xmlhttprequest.js (hunk 7 above)
Comment (avaer) [reply lib/xmlhttprequest.js:318]: Yeah, I think we can probably just pass the body through.

**Review by avaer — COMMENTED** [review]
Looks good -- only thing I would change is revert the comma dangling for existing code.

Not because I think dangling commas are bad -- but this is a fork we'll want to pull down from later and that will make it needlessly more painful.

**Review by avaer — APPROVED** [review]
